name: Automatically Publish Draft Release

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Publish Draft Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
      
